const courses = [
  {
    _id: "1",
    name: "Desert Beginner",
    image: "/images/desert-card.png",
    description: "Learn basic survival skills in the hot desert environment.",
    length: "3 Days",
    location: "Panamint Springs, CA",
    category: "Beginner",
    price: 749.95,
    date: "March 2020",
  },
  {
    _id: "2",
    name: "Tundra Beginner",
    image: "/images/tundra-card.png",
    description: "Learn basic survival skills in the cold tundra environment.",
    length: "3 Days",
    location: "Mount Washington, NH",
    category: "Beginner",
    price: 749.95,
    date: "October 2020",
  },
  {
    _id: "3",
    name: "Tropical Beginner",
    image: "/images/tropical-card.png",
    description:
      "Learn basic survival skills in the humid tropical environment.",
    length: "3 Days",
    location: "Everglades National Park, FL",
    category: "Beginner",
    price: 749.95,
    date: "May 2021",
  },
  {
    _id: "4",
    name: "Desert Intermediate",
    image: "/images/desert-card.png",
    description: "Learn basic survival skills in the hot desert environment.",
    length: "5 Days",
    location: "Panamint Springs, CA",
    category: "Intermediate",
    price: 1249.95,
    date: "April 2021",
  },
  {
    _id: "5",
    name: "Tundra Intermediate",
    image: "/images/tundra-card.png",
    description: "Learn basic survival skills in the cold tundra environment.",
    length: "5 Days",
    location: "Mount Washington, NH",
    category: "Intermediate",
    price: 1249.95,
    date: "November 2020",
  },
  {
    _id: "6",
    name: "Tropical Intermediate",
    image: "/images/tropical-card.png",
    description:
      "Learn basic survival skills in the humid tropical environment.",
    length: "5 Days",
    location: "Everglades National Park, FL",
    category: "Intermediate",
    price: 1249.95,
    date: "June 2021",
  },
  {
    _id: "7",
    name: "Desert Advanced",
    image: "/images/desert-card.png",
    description: "Learn basic survival skills in the hot desert environment.",
    length: "10 Days",
    location: "Panamint Springs, CA",
    category: "Advanced",
    price: 2499.95,
    date: "June 2021",
  },
  {
    _id: "8",
    name: "Tundra Advanced",
    image: "/images/tundra-card.png",
    description: "Learn basic survival skills in the cold tundra environment.",
    length: "10 Days",
    location: "Mount Washington, NH",
    category: "Advanced",
    price: 2499.95,
    date: "December 2020",
  },
  {
    _id: "9",
    name: "Tropical Advanced",
    image: "/images/tropical-card.png",
    description:
      "Learn basic survival skills in the humid tropical environment.",
    length: "10 Days",
    location: "Everglades National Park, FL",
    category: "Advanced",
    price: 2499.95,
    date: "July 2021",
  },
];

export default courses;
